apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - name: http
      protocol: TCP
      port: 31001
      nodePort: 31001
      targetPort: nodejs-port
  type: NodePort
